### PR TITLE
Fixing parameter managment

### PR DESCRIPTION
**Pull request by Chabrier**
try to fix parameter management

### CODE REVIEW

**Comment by quesnel** [comment]
I investigate the problem.

**Comment by quesnel** [comment]
I just pushed patches. Can you test? They are on my master branch (https://github.com/quesnel/vle.git)

**Comment by Chabrier** [comment]
Much better, error on parameters escape the processes.
Normal behaviour does work.

maybe remaining this, but not important:

```
Expe$ mpirun -n 2 cvle -P 2CV 2CV-parcelle.vpz -t theTemplate.csv
debug: main-mpi starts
debug: main-mpi starts
block size: 5000
package   : 2CV
timeout   : 0
input csv : stdin
output csv: stdout
workspace prefix: 
vpz       : 2CV-parcelle.vpz
```

stay blocked, but this does work:

```
Expe$ cvle -P 2CV 2CV-parcelle.vpz -t theTemplate.csv
debug: main-mpi starts
cvle needs two processors.
```

**Comment by quesnel** [comment]
Ok. I fix the template generation process. Can you check the new patch (always on my master branch).

**Comment by Chabrier** [comment]
Perfect!

**Comment by quesnel** [comment]
Thank you for the tests. I pushed commits on vle-forge/master.

**Comment by quesnel** [comment]
@Chabrier I cherry-picked and amended commits from master branch to the old master2.0.
Can you test cvle from my master2.0 branch?

**Comment by Chabrier** [comment]
Remaining PB on 2.0:
## Not working
```
Expe$ cvle-2.0 -P 2CV 2CV-parcelle.vpz -t ./theTemplate.csv
debug: Generates template file
Failed to generate template file: Path::operator/(): expected a relative path
```
## Working on 2.1
```
Expe$ cvle-2.1 -P 2CV 2CV-parcelle.vpz -t ./theTemplate.csv
debug: Generates template file
```

same problem on 2.0 with regular behaviuor
```
mpirun -n 2 cvle-2.0 -P 2CV 2CV-parcelle.vpz -i template.csv -o restemplate.csv
block size: 5000
package   : 2CV
timeout   : 0
input csv : template.csv
output csv: restemplate.csv
workspace prefix: 
vpz       : 2CV-parcelle.vpz
worker fails: Path::operator/(): expected a relative path
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 1 in communicator MPI_COMM_WORLD
with errorcode -4.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
```

**Pull request closed without merging**
